export type Product = {
  product_id: string;
  product_name: string;
  slug: string;
  price: number;
  old_price: number;
  category: string;
  brand: string;
  sku: string;
  rating: number;
  reviews: number;
  stock: number;
  image: string;
  badge?: string;
  description: string;
  benefits: string[];
  ingredients: string[];
  nutrition: { label: string; value: string }[];
};

const img = (q: string, seed: number) =>
  `https://images.unsplash.com/photo-${q}?auto=format&fit=crop&w=900&q=80&sig=${seed}`;

export const products: Product[] = [
  {
    product_id: "P001",
    product_name: "Gold Standard Whey Protein",
    slug: "1",
    price: 49.99,
    old_price: 64.99,
    category: "Protein",
    brand: "VitaCore",
    sku: "VC-WHEY-001",
    rating: 4.8,
    reviews: 1284,
    stock: 42,
    image: img("1579722821273-0f6c1f8b7b3a", 1),
    badge: "Best Seller",
    description:
      "Premium whey protein powder with 24g of high-quality protein per serving. Supports muscle recovery and growth.",
    benefits: ["24g Protein per serving", "5.5g BCAAs", "Fast absorbing", "Low sugar"],
    ingredients: ["Whey Protein Isolate", "Whey Protein Concentrate", "Natural Flavors", "Stevia"],
    nutrition: [
      { label: "Calories", value: "120" },
      { label: "Protein", value: "24g" },
      { label: "Carbs", value: "3g" },
      { label: "Fat", value: "1.5g" },
    ],
  },
  {
    product_id: "P002",
    product_name: "Pure Whey Isolate 90",
    slug: "2",
    price: 59.99,
    old_price: 79.99,
    category: "Protein",
    brand: "PureFit",
    sku: "PF-ISO-002",
    rating: 4.9,
    reviews: 892,
    stock: 31,
    image: img("1593095948071-474c5cc2989d", 2),
    badge: "New",
    description: "Ultra-pure whey isolate with 27g of protein and zero sugar per scoop.",
    benefits: ["27g Pure Protein", "Zero sugar", "Lactose-free", "Rapid absorption"],
    ingredients: ["Whey Protein Isolate", "Cocoa", "Natural Flavor", "Sucralose"],
    nutrition: [
      { label: "Calories", value: "110" },
      { label: "Protein", value: "27g" },
      { label: "Carbs", value: "1g" },
      { label: "Fat", value: "0.5g" },
    ],
  },
  {
    product_id: "P003",
    product_name: "Omega-3 Fish Oil 1200mg",
    slug: "3",
    price: 24.99,
    old_price: 34.99,
    category: "Vitamins",
    brand: "VitaCore",
    sku: "VC-OMG-003",
    rating: 4.7,
    reviews: 2103,
    stock: 120,
    image: img("1550572017-edd951b55104", 3),
    description: "High-potency fish oil for heart, brain, and joint health.",
    benefits: ["Heart health", "Brain support", "Joint comfort", "Burpless formula"],
    ingredients: ["Fish Oil", "EPA", "DHA", "Vitamin E"],
    nutrition: [
      { label: "Serving", value: "1 softgel" },
      { label: "EPA", value: "720mg" },
      { label: "DHA", value: "480mg" },
    ],
  },
  {
    product_id: "P004",
    product_name: "Daily Multivitamin Complex",
    slug: "4",
    price: 19.99,
    old_price: 29.99,
    category: "Vitamins",
    brand: "PureFit",
    sku: "PF-MULT-004",
    rating: 4.6,
    reviews: 1567,
    stock: 88,
    image: img("1584308666744-24d5c474f2ae", 4),
    description: "Complete daily multivitamin with 23 essential vitamins and minerals.",
    benefits: ["Daily nutrition", "Energy support", "Immune boost", "Once daily"],
    ingredients: ["Vitamin A, C, D, E, K", "B-Complex", "Iron", "Zinc", "Magnesium"],
    nutrition: [{ label: "Serving", value: "1 tablet" }],
  },
  {
    product_id: "P005",
    product_name: "Vitamin D3 5000 IU",
    slug: "5",
    price: 14.99,
    old_price: 22.99,
    category: "Vitamins",
    brand: "SunWell",
    sku: "SW-D3-005",
    rating: 4.9,
    reviews: 3421,
    stock: 200,
    image: img("1556909114-f6e7ad7d3136", 5),
    badge: "Top Rated",
    description: "Maximum strength Vitamin D3 for bone, immune, and mood support.",
    benefits: ["Bone health", "Immune support", "Mood balance", "5000 IU per softgel"],
    ingredients: ["Vitamin D3 (Cholecalciferol)", "Olive Oil", "Gelatin"],
    nutrition: [{ label: "Vitamin D3", value: "125mcg (5000 IU)" }],
  },
  {
    product_id: "P006",
    product_name: "Marine Collagen Peptides",
    slug: "6",
    price: 39.99,
    old_price: 54.99,
    category: "Beauty",
    brand: "GlowLab",
    sku: "GL-COL-006",
    rating: 4.8,
    reviews: 945,
    stock: 56,
    image: img("1610725664285-7c57e6eeac3f", 6),
    description: "Hydrolyzed marine collagen for radiant skin, hair, and nails.",
    benefits: ["Skin elasticity", "Stronger hair & nails", "Joint support", "Unflavored"],
    ingredients: ["Hydrolyzed Marine Collagen", "Vitamin C"],
    nutrition: [
      { label: "Collagen", value: "10g" },
      { label: "Protein", value: "10g" },
    ],
  },
  {
    product_id: "P007",
    product_name: "Micronized Creatine Monohydrate",
    slug: "7",
    price: 27.99,
    old_price: 39.99,
    category: "Performance",
    brand: "PureFit",
    sku: "PF-CRT-007",
    rating: 4.9,
    reviews: 2890,
    stock: 75,
    image: img("1607019578544-9bba3c8a04bd", 7),
    badge: "Best Seller",
    description: "Pure micronized creatine to boost strength, power, and lean mass.",
    benefits: ["Strength gains", "Faster recovery", "Lean muscle", "Unflavored"],
    ingredients: ["Creatine Monohydrate"],
    nutrition: [{ label: "Creatine", value: "5g" }],
  },
  {
    product_id: "P008",
    product_name: "BCAA Recovery Blend",
    slug: "8",
    price: 32.99,
    old_price: 44.99,
    category: "Performance",
    brand: "VitaCore",
    sku: "VC-BCAA-008",
    rating: 4.6,
    reviews: 712,
    stock: 60,
    image: img("1622818425825-cce63f7ec55a", 8),
    description: "2:1:1 BCAA blend for muscle recovery and reduced soreness.",
    benefits: ["Faster recovery", "Less soreness", "Hydration", "Refreshing taste"],
    ingredients: ["L-Leucine", "L-Isoleucine", "L-Valine", "Electrolytes"],
    nutrition: [{ label: "BCAAs", value: "7g" }],
  },
  {
    product_id: "P009",
    product_name: "Explosive Pre-Workout",
    slug: "9",
    price: 42.99,
    old_price: 59.99,
    category: "Performance",
    brand: "Apex",
    sku: "AX-PRE-009",
    rating: 4.7,
    reviews: 1456,
    stock: 38,
    image: img("1593095948071-474c5cc2989d", 9),
    badge: "Hot",
    description: "High-stim pre-workout for intense pumps, focus, and endurance.",
    benefits: ["Insane pumps", "Laser focus", "Endurance", "300mg caffeine"],
    ingredients: ["Citrulline Malate", "Beta-Alanine", "Caffeine", "L-Theanine"],
    nutrition: [{ label: "Caffeine", value: "300mg" }],
  },
  {
    product_id: "P010",
    product_name: "Thermogenic Fat Burner",
    slug: "10",
    price: 36.99,
    old_price: 49.99,
    category: "Weight Loss",
    brand: "Apex",
    sku: "AX-FB-010",
    rating: 4.4,
    reviews: 678,
    stock: 44,
    image: img("1505751172876-fa1923c5c528", 10),
    description: "Advanced thermogenic to support fat loss, energy, and appetite control.",
    benefits: ["Boost metabolism", "Curb appetite", "Clean energy", "Mood support"],
    ingredients: ["Green Tea Extract", "L-Carnitine", "Caffeine", "Cayenne"],
    nutrition: [{ label: "Caffeine", value: "200mg" }],
  },
  {
    product_id: "P011",
    product_name: "Hydration Electrolyte Powder",
    slug: "11",
    price: 22.99,
    old_price: 29.99,
    category: "Hydration",
    brand: "PureFit",
    sku: "PF-ELC-011",
    rating: 4.8,
    reviews: 1102,
    stock: 95,
    image: img("1622818425825-cce63f7ec55a", 11),
    description: "Sugar-free electrolyte powder to keep you hydrated and energized.",
    benefits: ["Rapid hydration", "Zero sugar", "Natural flavors", "On-the-go"],
    ingredients: ["Sodium", "Potassium", "Magnesium", "Vitamin C"],
    nutrition: [{ label: "Calories", value: "10" }],
  },
  {
    product_id: "P012",
    product_name: "Super Greens Powder",
    slug: "12",
    price: 47.99,
    old_price: 64.99,
    category: "Superfoods",
    brand: "GreenLeaf",
    sku: "GL-GRN-012",
    rating: 4.7,
    reviews: 1820,
    stock: 67,
    image: img("1610725664285-7c57e6eeac3f", 12),
    badge: "New",
    description: "Daily greens blend with 40+ superfoods, probiotics, and adaptogens.",
    benefits: ["Daily nutrition", "Gut health", "Immune support", "Natural energy"],
    ingredients: ["Spirulina", "Chlorella", "Wheatgrass", "Probiotics", "Ashwagandha"],
    nutrition: [
      { label: "Servings", value: "30" },
      { label: "Probiotics", value: "5 Billion CFU" },
    ],
  },
];

export const getProduct = (id: string) => products.find((p) => p.slug === id || p.product_id === id);
